/**
 * سجل الأيقونات المنتقاة (Lucide خطية رفيعة) مع كلمات بحث عربية لمنتقي الأيقونات.
 * يُشار للأيقونة في البيانات بصيغة "lucide:<name>".
 */
import {
  Accessibility, Activity, AlarmClock, Apple, Archive, Atom, Award, Baby, Backpack, BadgeCheck, Banknote, Bell, Bike, Binary, Blocks, BookMarked,
  BookOpen, BookUser, Bookmark, Bot, Box, Brain, Briefcase, Building, Building2, Bus, Calculator, Calendar, CalendarCheck, CalendarClock,
  CalendarDays, CalendarHeart, Camera, Car, ChartBar, ChartLine, ChartPie, CircleCheck, CircleDot, CircleHelp, ClipboardCheck, ClipboardList,
  Clock, Cloud, Code2, Coffee, Coins, Compass, Construction, Contact, Cpu, CreditCard, Crown, Database, Diamond, Dna, DoorOpen, Dumbbell,
  Factory, File, FileCheck, FilePen, FileText, Files, Film, Fingerprint, Flag, FlaskConical, Flower2, Folder, FolderOpen, Footprints, Gamepad2,
  Gavel, Gem, Gift, Globe, GraduationCap, HandCoins, HandHeart, Handshake, Hammer, HardDrive, Headphones, Heart, HeartHandshake, HeartPulse,
  Hospital, Hourglass, House, IdCard, Image, Inbox, Info, Kanban, KeyRound, Landmark, Languages, Laptop, LayoutDashboard, LayoutGrid, Leaf,
  Library, LifeBuoy, Lightbulb, List, ListChecks, ListTodo, Lock, Mail, Map as MapIcon, MapPin, Medal, Megaphone, MessageCircle, MessagesSquare,
  Microscope, Monitor, Mountain, Music, Newspaper, NotebookPen, NotebookText, Orbit, Package, Palette, PencilRuler, Percent, Phone, PiggyBank,
  Pin, Plane, Presentation, Printer, Puzzle, QrCode, Receipt, Rocket, Ruler, Scale, School, ScrollText, Search, Send, Server, Settings,
  Settings2, Shapes, ShieldCheck, ShieldHalf, ShoppingCart, Signature, Siren, Smartphone, Smile, Sparkles, Stamp, Star, Stethoscope, Store,
  Sun, Sunrise, Table2, Tag, Target, Telescope, Tent, TestTube, Ticket, Timer, TrafficCone, TreePine, TriangleAlert, Trophy, Truck, Tv,
  UserCog, UserPlus, UserCheck, UserX, UserRound, Users, UsersRound, ArrowLeftRight, CalendarX, ClipboardPen, Grid3x3, Utensils, Video, Wallet, Warehouse, Wifi, Workflow, Wrench, Zap, type LucideIcon,
} from "lucide-react";

export interface IconDef {
  name: string;
  icon: LucideIcon;
  /** كلمات البحث بالعربية */
  keywords: string;
}

const def = (name: string, icon: LucideIcon, keywords: string): IconDef => ({ name, icon, keywords });

export const ICONS: readonly IconDef[] = [
  def("layout-dashboard", LayoutDashboard, "لوحة قيادة مؤشرات"),
  def("kanban", Kanban, "لوحة كانبان مهام"),
  def("list-checks", ListChecks, "قائمة تحقق مهام"),
  def("list-todo", ListTodo, "مهام قائمة"),
  def("clipboard-check", ClipboardCheck, "تقييم زيارة تحقق"),
  def("clipboard-list", ClipboardList, "قائمة حافظة"),
  def("target", Target, "هدف استراتيجية"),
  def("flag", Flag, "علم هدف"),
  def("rocket", Rocket, "إطلاق مبادرة صاروخ"),
  def("lightbulb", Lightbulb, "فكرة مقترح"),
  def("sparkles", Sparkles, "مبادرة تميز لمعان"),
  def("gavel", Gavel, "قرار مجلس"),
  def("scale", Scale, "سياسة ميزان عدل"),
  def("landmark", Landmark, "إدارة مؤسسة"),
  def("building", Building, "مبنى"),
  def("building-2", Building2, "مبنى مكاتب فرع"),
  def("school", School, "مدرسة"),
  def("graduation-cap", GraduationCap, "تخرج أكاديمي تعليم"),
  def("book-open", BookOpen, "كتاب دليل قراءة"),
  def("book-marked", BookMarked, "كتاب دليل"),
  def("bookmark", Bookmark, "إشارة مرجعية حفظ"),
  def("book-user", BookUser, "دليل موظفين"),
  def("library", Library, "مكتبة"),
  def("notebook-pen", NotebookPen, "ملاحظات دفتر"),
  def("notebook-text", NotebookText, "دفتر"),
  def("scroll-text", ScrollText, "لائحة سياسة وثيقة"),
  def("file-text", FileText, "ملف مستند"),
  def("file", File, "ملف ورقة"),
  def("file-pen", FilePen, "تحرير مستند"),
  def("file-check", FileCheck, "مستند معتمد"),
  def("files", Files, "ملفات"),
  def("folder", Folder, "مجلد"),
  def("folder-open", FolderOpen, "مجلد مفتوح"),
  def("archive", Archive, "أرشيف"),
  def("pencil-ruler", PencilRuler, "مناهج تصميم"),
  def("ruler", Ruler, "مسطرة"),
  def("calculator", Calculator, "حاسبة رياضيات محاسبة"),
  def("microscope", Microscope, "علوم مختبر"),
  def("flask-conical", FlaskConical, "كيمياء مختبر"),
  def("test-tube", TestTube, "مختبر"),
  def("atom", Atom, "فيزياء ذرة"),
  def("dna", Dna, "أحياء"),
  def("telescope", Telescope, "فلك"),
  def("orbit", Orbit, "فضاء"),
  def("brain", Brain, "تفكير عقل"),
  def("languages", Languages, "لغات"),
  def("globe", Globe, "عالم جغرافيا"),
  def("map", MapIcon, "خريطة"),
  def("map-pin", MapPin, "موقع"),
  def("presentation", Presentation, "عرض تدريب"),
  def("users", Users, "طلاب مستخدمون فريق"),
  def("users-round", UsersRound, "اجتماع فريق"),
  def("user-round", UserRound, "شخص مستخدم"),
  def("user-cog", UserCog, "إدارة مستخدم"),
  def("user-plus", UserPlus, "قبول تسجيل طالب جديد"),
  def("user-check", UserCheck, "حضور تحضير"),
  def("user-x", UserX, "غياب"),
  def("arrow-left-right", ArrowLeftRight, "تحويل نقل"),
  def("calendar-x", CalendarX, "إجازة غياب"),
  def("clipboard-pen", ClipboardPen, "سلوك ملاحظة"),
  def("grid-3x3", Grid3x3, "جدول حصص"),
  def("contact", Contact, "جهة اتصال"),
  def("id-card", IdCard, "هوية موظف"),
  def("baby", Baby, "رياض أطفال"),
  def("backpack", Backpack, "حقيبة طالب"),
  def("briefcase", Briefcase, "توظيف عمل"),
  def("handshake", Handshake, "شراكة اتفاق"),
  def("hand-heart", HandHeart, "رعاية ترحيب"),
  def("heart-handshake", HeartHandshake, "تطوع"),
  def("heart", Heart, "قلب"),
  def("heart-pulse", HeartPulse, "صحة عيادة"),
  def("stethoscope", Stethoscope, "طبي عيادة"),
  def("hospital", Hospital, "مستشفى"),
  def("apple", Apple, "تغذية مقصف"),
  def("utensils", Utensils, "مقصف وجبات"),
  def("coffee", Coffee, "استراحة"),
  def("wallet", Wallet, "مالية محفظة"),
  def("banknote", Banknote, "نقد مال"),
  def("coins", Coins, "رسوم مبالغ"),
  def("hand-coins", HandCoins, "تحصيل مدفوعات"),
  def("piggy-bank", PiggyBank, "ادخار موازنة"),
  def("credit-card", CreditCard, "بطاقة دفع"),
  def("receipt", Receipt, "فاتورة سند"),
  def("percent", Percent, "خصم نسبة"),
  def("chart-bar", ChartBar, "تقرير أعمدة"),
  def("chart-line", ChartLine, "اتجاه تقرير"),
  def("chart-pie", ChartPie, "توزيع تقرير"),
  def("activity", Activity, "نشاط"),
  def("database", Database, "قاعدة بيانات"),
  def("table-2", Table2, "جدول"),
  def("layout-grid", LayoutGrid, "شبكة معرض"),
  def("list", List, "قائمة"),
  def("calendar", Calendar, "تقويم"),
  def("calendar-days", CalendarDays, "تقويم أيام"),
  def("calendar-check", CalendarCheck, "موعد"),
  def("calendar-clock", CalendarClock, "جدول مواعيد"),
  def("calendar-heart", CalendarHeart, "فعاليات مناسبات"),
  def("clock", Clock, "وقت"),
  def("alarm-clock", AlarmClock, "منبه تذكير"),
  def("timer", Timer, "مؤقت"),
  def("hourglass", Hourglass, "انتظار"),
  def("hammer", Hammer, "صيانة"),
  def("wrench", Wrench, "صيانة عمليات"),
  def("construction", Construction, "قيد الإنشاء"),
  def("traffic-cone", TrafficCone, "تنبيه"),
  def("factory", Factory, "مصنع"),
  def("warehouse", Warehouse, "مستودع مخزون"),
  def("package", Package, "مخزون طرد"),
  def("box", Box, "صندوق"),
  def("truck", Truck, "توريد شحن"),
  def("shopping-cart", ShoppingCart, "مشتريات"),
  def("store", Store, "متجر"),
  def("bus", Bus, "نقل مدرسي حافلة"),
  def("car", Car, "سيارة"),
  def("plane", Plane, "رحلة"),
  def("tent", Tent, "مخيم نشاط"),
  def("mountain", Mountain, "رحلة جبل"),
  def("tree-pine", TreePine, "بيئة"),
  def("leaf", Leaf, "بيئة"),
  def("flower-2", Flower2, "زهرة"),
  def("sun", Sun, "شمس"),
  def("sunrise", Sunrise, "صباح"),
  def("cloud", Cloud, "سحابة"),
  def("megaphone", Megaphone, "إعلان تواصل"),
  def("messages-square", MessagesSquare, "رسائل تواصل"),
  def("message-circle", MessageCircle, "محادثة"),
  def("mail", Mail, "بريد"),
  def("send", Send, "إرسال"),
  def("phone", Phone, "هاتف"),
  def("smartphone", Smartphone, "جوال"),
  def("newspaper", Newspaper, "أخبار نشرة"),
  def("bell", Bell, "تنبيه إشعار"),
  def("inbox", Inbox, "وارد"),
  def("settings", Settings, "إعدادات"),
  def("settings-2", Settings2, "إعدادات نظام"),
  def("shield-check", ShieldCheck, "أمان حماية"),
  def("shield-half", ShieldHalf, "سلامة"),
  def("lock", Lock, "قفل"),
  def("key-round", KeyRound, "مفتاح"),
  def("fingerprint", Fingerprint, "بصمة"),
  def("qr-code", QrCode, "رمز"),
  def("siren", Siren, "طوارئ"),
  def("triangle-alert", TriangleAlert, "تحذير"),
  def("info", Info, "معلومات"),
  def("circle-help", CircleHelp, "مساعدة"),
  def("life-buoy", LifeBuoy, "دعم فني"),
  def("compass", Compass, "دليل استكشاف"),
  def("server", Server, "خادم"),
  def("hard-drive", HardDrive, "نسخ احتياطي"),
  def("cpu", Cpu, "تقنية"),
  def("laptop", Laptop, "حاسب"),
  def("monitor", Monitor, "شاشة"),
  def("tv", Tv, "تلفاز"),
  def("wifi", Wifi, "شبكة"),
  def("printer", Printer, "طباعة"),
  def("code-2", Code2, "برمجة"),
  def("binary", Binary, "حاسب"),
  def("workflow", Workflow, "سير عمل"),
  def("blocks", Blocks, "مكونات"),
  def("puzzle", Puzzle, "لغز"),
  def("shapes", Shapes, "أشكال"),
  def("palette", Palette, "فنون ألوان"),
  def("music", Music, "موسيقى"),
  def("camera", Camera, "تصوير"),
  def("image", Image, "صورة"),
  def("film", Film, "فيلم"),
  def("video", Video, "فيديو"),
  def("headphones", Headphones, "استماع"),
  def("gamepad-2", Gamepad2, "ألعاب"),
  def("dumbbell", Dumbbell, "رياضة"),
  def("bike", Bike, "دراجة"),
  def("footprints", Footprints, "خطوات"),
  def("trophy", Trophy, "إنجاز جائزة"),
  def("medal", Medal, "ميدالية تفوق"),
  def("award", Award, "تكريم"),
  def("badge-check", BadgeCheck, "اعتماد"),
  def("crown", Crown, "تميز"),
  def("gem", Gem, "جوهرة"),
  def("diamond", Diamond, "ماسة"),
  def("star", Star, "نجمة مفضلة"),
  def("gift", Gift, "هدية"),
  def("ticket", Ticket, "تذكرة"),
  def("tag", Tag, "وسم"),
  def("stamp", Stamp, "ختم"),
  def("signature", Signature, "توقيع"),
  def("pin", Pin, "تثبيت"),
  def("door-open", DoorOpen, "زوار"),
  def("accessibility", Accessibility, "وصول"),
  def("smile", Smile, "ابتسامة"),
  def("bot", Bot, "مساعد ذكي"),
  def("zap", Zap, "أتمتة سرعة"),
  def("circle-check", CircleCheck, "مكتمل"),
  def("circle-dot", CircleDot, "حالة"),
  def("search", Search, "بحث"),
  def("house", House, "رئيسية"),
];

export const ICON_MAP: ReadonlyMap<string, LucideIcon> = new Map(ICONS.map((i) => [i.name, i.icon]));
